//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardsOnTheBrazos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Event
    {
        public System.Guid EventId { get; set; }
        [Display(Name = "Post")]
        public string EventPost { get; set; }
        [Display(Name = "Image")]
        public string EventPicture { get; set; }
    }
}
